### ISSUE TITLE
Did you get this to work?

### ISSUE THREAD

**Issue by Nyholm** [EugenMayer/docker-image-docker-client#1]
When I build this image and execute `docker login` in it I get: 

> Warning: failed to get default registry endpoint from daemon (Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?). Using system default: https://index.docker.io/v1/

**Comment by EugenMayer** [comment]
yes this works. You have to ensure to either expose the credentials for the docker remote socket or mount a local socket - as you need it.
